Repository wecode-bootcamp-korea/19-1st-the_meat-frontend, pull requests merged in 2021-04, with the labels that each got.

#2 [19기 이재영] Main 신상품 layout 진행중
  public/Data/Banner.json
  public/Data/Card.json
  public/Data/CardList.json
  public/images/meatimg/MainLogo.jpg
  public/images/meatimg/mainLogo.png
  public/index.html
  src/Pages/CommonComponent/CommonComponent.js
  src/Pages/CommonComponent/CommonComponent.scss
  src/Pages/Main/ArticleDiscount/ArticleDiscount.js
  src/Pages/Main/ArticleDiscount/ArticleDiscount.scss
  src/Pages/Main/ArticleMd/ArticleMd.js
  src/Pages/Main/ArticleMd/ArticleMd.scss
  src/Pages/Main/Banner/Banner.js
  src/Pages/Main/Banner/Banner.scss
  src/Pages/Main/Component/Card.js
  src/Pages/Main/Component/Card.scss
  src/Pages/Main/Component/SmallCard.js
  src/Pages/Main/Component/SmallCard.scss
  src/Pages/Main/Main.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/Nav.scss
  src/Style/common.scss
  src/Style/reset.scss
Labels: Status: 리뷰 요청, Status: 수정 요청, Status: 추가 기능 구현중

#1 [19기 서민석] 회원가입 페이지 끝
  README.md
  src/Pages/Signup/Components/Form.js
  src/Pages/Signup/Components/Form.scss
  src/Pages/Signup/Components/Input.js
  src/Pages/Signup/Components/Input.scss
  src/Pages/Signup/Components/Layout.js
  src/Pages/Signup/Components/Layout.scss
  src/Pages/Signup/Components/WarningPassword.js
  src/Pages/Signup/Components/WarningPassword.scss
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
Labels: Status: 리뷰 요청

#5 [19기 서민석] 로그인페이지 레이아웃 설정, state 설정, 함수 설정
  src/Pages/Login/Component/Button.js
  src/Pages/Login/Component/Button.scss
  src/Pages/Login/Component/Form.js
  src/Pages/Login/Component/Form.scss
  src/Pages/Login/Component/Input.js
  src/Pages/Login/Component/Input.scss
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
Labels: Status: 리뷰 요청

#3 [19기 이재영] Nav Category 완료
  public/Data/CategoryList.json
  public/images/meatimg/001.jpg
  public/images/meatimg/002.jpg
  public/images/meatimg/003.jpg
  public/images/meatimg/004.jpg
  public/images/meatimg/닭고기.jpg
  public/images/meatimg/돼지고기.jpg
  public/images/meatimg/소고기.jpg
  public/images/meatimg/소스류.jpg
  public/images/meatimg/양고기.jpg
  public/images/meatimg/염소고기.jpg
  public/images/meatimg/채소류.jpg
  public/images/meatimg/한돈.jpg
  src/Pages/Main/Main.js
  src/Pages/Nav/Nav.js
  src/Pages/Nav/Nav.scss
  src/Pages/Nav/NavCategory.js
  src/Pages/Nav/NavCategory.scss
  src/Style/common.scss
  src/Style/reset.scss
Labels: Status: Accepted

#7 [19기 서민석] 상세페이지 추천제품 slide 추가 , 리뷰 반영
  public/data/Data.json
  src/Pages/DetailFile/Components/Button.js
  src/Pages/DetailFile/Components/Button.scss
  src/Pages/DetailFile/Components/Content.js
  src/Pages/DetailFile/Components/Content.scss
  src/Pages/DetailFile/Components/Image.js
  src/Pages/DetailFile/Components/Image.scss
  src/Pages/DetailFile/Components/Layout.js
  src/Pages/DetailFile/Components/Layout.scss
  src/Pages/DetailFile/Components/ProductList.scss
  src/Pages/DetailFile/Components/ProductsList.js
  src/Pages/DetailFile/Components/Recommand.js
  src/Pages/DetailFile/Components/Recommand.scss
  src/Pages/DetailFile/Components/Title.js
  src/Pages/DetailFile/Components/Title.scss
  src/Pages/DetailFile/DetailFile.js
  src/Pages/DetailFile/DetailFile.scss
  src/Pages/Slider/Slider.js
  src/Pages/Slider/Slider.scss
Labels: Status: 리뷰 요청

#10 [19기 서민석] 오류 수정
  src/Pages/Login/Component/Form.js
  src/Pages/Signup/Signup.js
Labels: Status: 수정 요청

#11 [19기 이재영] Nav css 수정완료
  public/Data/CategoryList.json
  src/Pages/Nav/NavCategory.scss
Labels: Status: 리뷰 요청

#6 [19기 홍진아] Category 페이지 완료
  public/data/ProductBoxData.json
  public/images/meatimg/cow.jpg
  public/index.html
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Pages/Category/Component/LeftSortBox.js
  src/Pages/Category/Component/Product.js
  src/Pages/Category/Component/Product.scss
  src/Pages/Category/Component/ProductBox.scss
  src/Pages/Category/Component/ProductCart.js
  src/Pages/Category/Component/ProductCart.scss
  src/Pages/Category/Component/ProductImg.js
  src/Pages/Category/Component/ProductImg.scss
  src/Pages/Category/Component/ProductTag.js
  src/Pages/Category/Component/ProductTag.scss
  src/Pages/Category/Component/ProductText.js
  src/Pages/Category/Component/ProductText.scss
  src/Pages/Category/Component/RightSortBox.js
  src/Style/common.scss
Labels: Status: Conflict 발생, Status: 추가 기능 구현중

#8 [19기 이재영] Main 완료
  public/Data/Banner.json
  public/Data/CardNew.json
  src/Pages/Main/ArticleDiscount/ArticleDiscount.js
  src/Pages/Main/ArticleMd/ArticleMd.js
  src/Pages/Main/ArticleMd/ArticleMd.scss
  src/Pages/Main/ArticleNewProduct/ArticleNewProduct.js
  src/Pages/Main/ArticleNewProduct/ArticleNewProduct.scss
  src/Pages/Main/Banner/Banner.scss
  src/Pages/Main/Component/Card.js
  src/Pages/Main/Component/SmallCard.js
  src/Pages/Main/Main.js
  src/Pages/Nav/NavCategory.js
  src/config.js
Labels: Status: 리뷰 요청

#9 [19기 서민석] 총 금액 나오는 것 확인
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Components/Contents.js
  src/Pages/Basket/Components/Contents.scss
  src/Pages/Basket/Components/ContentsComponents/Amount.js
  src/Pages/Basket/Components/ContentsComponents/Count.js
  src/Pages/Basket/Components/ContentsComponents/Delete.js
  src/Pages/Basket/Components/ContentsComponents/Image.js
  src/Pages/Basket/Components/ContentsComponents/Price.js
  src/Pages/Basket/Components/ContentsComponents/Title.js
  src/Pages/Basket/Components/Form.js
  src/Pages/Basket/Components/Layout.js
  src/Pages/Basket/Components/Layout.scss
  src/Pages/Basket/Components/Menu.js
  src/Pages/Basket/Components/Menu.scss
  src/Pages/Basket/Components/Order.js
  src/Pages/Basket/Components/Order.scss
  src/Pages/Basket/Components/Title.js
  src/Pages/Basket/Components/Title.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
